# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      # run tests!
      - run: gradle test
      - run:
          name: Replace MongoDB URI placeholder
          command: sed -i -e "s/replaceme/${PROD_MONGODB_URI}/g" tournamator-app/src/main/resources/application-prod.yml
      - run:
          name: Check URI is set correctly
          command: cat tournamator-app/src/main/resources/application-prod.yml
      - run: gradle buildDeployableJar
      - run:
          name: List current files
          command: ls -l
      - run:
          name: List files inside bootJar
          command: jar -tf tournamator-app/build/libs/tournamator-app.jar
      - persist_to_workspace:
          root: .
          paths:
            - tournamator-app/build/libs
            - Dockerfile
            - deploy
            - app.yaml

  deploy_prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Create .env file
          command: echo "DEPLOY_ENV=prod" > .env
      - run:
          name: Make sure files are right
          command: ls -a
      - run:
          name: Auth gCloud SDK
          command: bash ./deploy/gcloud-auth.sh
      - run:
          name: Deploy to gCloud
          command: bash ./deploy/gcloud-deploy.sh

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy_prod:
          requires:
            - build